### ISSUE TITLE
As a f-e guy, I want to use the simple docker and work with the UI.

### ISSUE THREAD

**Issue by dervalp** [CluedIn-io/Simple-Docker-Deployment#4]
Define the steps.

**Comment by rauljmz** [comment]
This was not the premise I was given, however, since the webapp when running natively usually works over port 3000, and the docker container is exposing port 80, there is no clash. Also, since the variables for domains are added to the host environment, they should be picked up OK by the webapp.

So basically I think it should *just work*. @dervalp please add info here if it does not.

**Comment by dervalp** [comment]
ok - I will.
